# Generated by Django 3.0.4 on 2020-03-21 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='updation_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
