# Generated by Django 3.0.4 on 2020-03-21 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_updation_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='My_Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ttle', models.CharField(max_length=100)),
            ],
        ),
    ]
